export const browserCoreExamples = [
  "shittimchest browser status",
  "shittimchest browser start",
  "shittimchest browser stop",
  "shittimchest browser tabs",
  "shittimchest browser open https://example.com",
  "shittimchest browser focus abcd1234",
  "shittimchest browser close abcd1234",
  "shittimchest browser screenshot",
  "shittimchest browser screenshot --full-page",
  "shittimchest browser screenshot --ref 12",
  "shittimchest browser snapshot",
  "shittimchest browser snapshot --format aria --limit 200",
  "shittimchest browser snapshot --efficient",
  "shittimchest browser snapshot --labels",
];

export const browserActionExamples = [
  "shittimchest browser navigate https://example.com",
  "shittimchest browser resize 1280 720",
  "shittimchest browser click 12 --double",
  'shittimchest browser type 23 "hello" --submit',
  "shittimchest browser press Enter",
  "shittimchest browser hover 44",
  "shittimchest browser drag 10 11",
  "shittimchest browser select 9 OptionA OptionB",
  "shittimchest browser upload /tmp/shittimchest/uploads/file.pdf",
  'shittimchest browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "shittimchest browser dialog --accept",
  'shittimchest browser wait --text "Done"',
  "shittimchest browser evaluate --fn '(el) => el.textContent' --ref 7",
  "shittimchest browser console --level error",
  "shittimchest browser pdf",
];
